import type { Config } from 'tailwindcss';
import typography from '@tailwindcss/typography';

export default {
    content: [
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                background: 'var(--background)',
                foreground: 'var(--foreground)',
                primary: '#5865F2',
                secondary: '#2F3136',
                success: '#57F287',
                warning: '#F7B500',
                neutral: '#DCDDDE',
                error: '#DC6060',
                'primary-dark': '#4757D6',
                primaryt: '#5865F235',
                'secondary-dark': '#1F2125',
                'success-dark': '#44D171',
                'warning-dark': '#D39A00',
                'neutral-dark': '#AAB1B6',
                dark: '#131313',
                'prose-dark': '#E2E8F0',
            },
        },
    },
    darkMode: 'class',
    plugins: [typography],
    safelist: [
        'font-bold',
        'italic',
        'text-foreground',
        'bg-secondary-dark',
        'p-4',
        'rounded-lg',
        'overflow-auto',
        'bg-secondary',
        'text-neutral',
        'px-1',
        'py-0.5',
        'rounded',
        'text-4xl',
        'm-8',
        'text-center',
        'text-white',
        'text-3xl',
        'mb-3',
        'text-2xl',
        'mb-2',
        'text-xl',
        'text-lg',
        'mb-1',
        'text-base',
        'list-disc',
        'pl-5',
        'mb-2',
        'pl-10',
        'list-decimal',
        'underline',
        'hover:text-primary-dark',
        'border-l-4',
        'border-primary',
        'pl-4',
        'text-neutral-dark',
        'border-t-[1px]',
        'relative',
    ],
} satisfies Config;
